# Generated by Django 3.1.5 on 2021-01-18 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='n/a', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='startDate',
            field=models.CharField(max_length=10),
        ),
    ]
